const conf = require('./conf')
const { getSource, getIndexUrl, getCCUrl, getCCSource} = require('./src/parse/detail')
const getGlobal = require('./src/getGlobal')
const debug = require('debug')('spride')
debug("start")
debug(process.env.NODE_ENV)
// getGlobal(conf.sprideURL.hqgq, getIndexUrl, getSource)
getGlobal(conf.sprideURL.cc, getCCUrl, getCCSource )
